source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZKeyboardManager_Example', :exclusive => true do
  pod 'DZKeyboardManager', :path => '../'
end

target 'DZKeyboardManager_Tests', :exclusive => true do
  pod 'DZKeyboardManager', :path => '../'

  pod 'FBSnapshotTestCase'
end
